# Generated by Django 4.2.16 on 2024-10-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contacts',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Контакты'),
        ),
    ]
