# Generated by Django 4.2.16 on 2024-10-14 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_company_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='contacts',
        ),
    ]
